logistics

diff --git a/bin/operations b/bin/operations
--- a/bin/operations
+++ b/bin/operations
@@ -269,6 +269,8 @@ function get-version() {
 #
 function set-version() {
 
+    debug-arguments "$@"
+
     local version=$1
     [ -z "${version}" ] && fail "'version' not specified"
 
@@ -280,9 +282,13 @@ function set-version() {
     # replace the first occurrence of <version>...</version> with our version
     #
 
+    debug "inserting version ${version}"
+
     local tmp_file=./.tmp
-    sed -e '1,/^ *<version>.*<\/version> *$/s/^\( *<version>\).*\(<\/version> *\)$/\1'${version}'\2/' ${pom_file} > ${tmp_file} || \
+
+    sed -e '1,/^ *<version>.*<\/version> */s/^\( *<version>\).*\(<\/version> *\)/\1'${version}'\2/' ${pom_file} > ${tmp_file} || \
         fail "failed to perform sed replacement"
+
     diff -q ${pom_file} ${tmp_file} > /dev/null && fail "no replacement was made in ${pom_file}"
     mv ${tmp_file} ${pom_file} || fail "failed to restore ${pom_file} from ${tmp_file}"
 }
@@ -1090,8 +1096,18 @@ function do-release() {
     git commit -m "release ${next_version}" && info "git commit ok" || fail "git commit failed"
 
     local tag=release-${next_version}
+    local tagged
 
-    git tag -m "release ${next_version}" "${tag}" && info "git tag ok, tagged with ${tag}" || fail "git tag failed"
+    if [[ ${tag} =~ SNAPSHOT ]]; then
+        #
+        # only tag repository if we're not a snapshot
+        #
+        info "current release is a snapshot, won't tag the repository"
+        tagged=false
+    else
+        git tag -m "release ${next_version}" "${tag}" && info "git tag ok, tagged with ${tag}" || fail "git tag failed"
+        tagged=true
+    fi
 
     git push --follow-tags && info "git push ok" || fail "git push failed"
 
@@ -1109,8 +1125,17 @@ function do-release() {
         install-release ${release_zip_file_path}
     fi
 
+    local msg="A new ${mode} version (${next_version}) was released"
+
+    if ${tagged}; then
+
+        msg="${msg}, committed to repository and tagged."
+    else
+        msg="${msg} and committed to repository."
+    fi
+
     info ""
-    info "A new ${mode} version (${next_version}) was released, committed to repository and tagged."
+    info ${msg}
     info "If you want to create an official GitHub release, use tag \"${tag}\" and the following binary: ${release_zip_file_path}"
     info ""
 
