release 2.4.2-SNAPSHOT-2

diff --git a/bin/operations b/bin/operations
--- a/bin/operations
+++ b/bin/operations
@@ -24,8 +24,6 @@ Global Options:
 
 Commands:
 
-    install [-f|--force]
-
     release <info|snapshot|minor|major|patch|"version-string">
 
         If 'info' is used, returns the current version information.
@@ -43,7 +41,26 @@ Commands:
         version. The repository can be the local Maven repository, a directory, a remote server,
         etc.
 
+        Upon release, the changes will be checked into the source repository, and a
+        'release-<version>' tag will be applied, unless the release is a snapshot, in which case the
+        repository won't be tagged. The changes will be pushed into the remote repository.
+
         Also see https://kb.novaordis.com/index.php/Public_Release_Procedure_for_Projects
+
+        Options:
+
+        --no-push - changes won't be pushed into the remote repository. Useful when the release
+          process takes place offline. The changes will have to be manually pushed later.
+
+        --no-tests - won't run the test suite upon release. Not usually recommended, unless we're
+          releasing a snapshot.
+
+
+    install [-f|--force]
+
+         Options:
+
+        --force - overwrites an already installed version.
 
      test - internal release tools testing shortcut. Advanced users only.
 
@@ -293,11 +310,14 @@ function set-version() {
     mv ${tmp_file} ${pom_file} || fail "failed to restore ${pom_file} from ${tmp_file}"
 }
 
-# mode can be 'major', 'minor', 'patch', 'snapshot' or a full version string.
-# If a full version string is provided, the function will verify that is a valid version string and the version it
-# specifies if newer than the current version.
+#
+# gets the current version as declared in POM and computes the version for the release
+# being processed. 'mode' can be "major", "minor", "patch", "snapshot" or a full version
+# string. If a full version string is provided, the function will verify that is a valid
+# version string and the version it # specifies if newer than the current version.
 # Sends the version string at stdout.
-function compute-next-version() {
+#
+function compute-release-version() {
 
     debug-arguments "$@"
 
@@ -445,6 +465,52 @@ function compute-next-version() {
         snapshot=${new_snapshot}
     fi
 
+    assemble-version-string "${major}" "${minor}" "${patch}" "${snapshot}"
+}
+
+#
+# gets the current version as declared in POM and computes the next patch snapshot.
+#
+
+function compute-next-version() {
+
+    debug-arguments "$@"
+
+    local current_version=$1
+    [ -z "${current_version}" ] && fail "'current_version' not specified"
+
+    local major
+    local minor
+    local patch
+    local snapshot
+
+    major=$(extract-version-component major ${current_version}) || exit 1
+    minor=$(extract-version-component minor ${current_version}) || exit 1
+    patch=$(extract-version-component patch ${current_version}) || exit 1
+    snapshot=$(extract-version-component snapshot ${current_version}) || exit 1
+
+    debug "major=${major}, minor=${minor}, patch=${patch}, snapshot=${snapshot}"
+
+    #
+    # we calculate the next logical snapshot
+    #
+    if [ -n "${snapshot}" ]; then
+        #
+        # we're a snapshot, increment it
+        #
+        snapshot=$(expr ${snapshot} + 1) || exit 1
+    else
+        #
+        # we're not a snapshot, increment the version to the next patch and initiate snapshot 1
+        #
+        if [ -z "${patch}" ]; then
+            patch=1
+        else
+            patch=$(expr ${patch} + 1) || exit 1
+        fi
+        [ -z "${minor}" ] && minor=0
+        snapshot=1
+    fi
     assemble-version-string "${major}" "${minor}" "${patch}" "${snapshot}"
 }
 
@@ -599,8 +665,9 @@ function get-artifact-base-name()
 }
 
 #
-# returns the artifact file name, as it will be generated by Maven, including base name, optionally version and
-# extension. It's either 'finalName' + extension (if exists) or 'artifactId' + version + extension.
+# returns the artifact file name (not the path), as it will be generated by Maven, including base name, optionally
+# version and extension. It's either 'finalName' + extension (if exists) or 'artifactId' + version + extension.
+# If built, the artifact file name is typically located under ${project_home}/target
 #
 function get-artifact-file-name()
 {
@@ -740,15 +807,13 @@ function get-dependencies()
 #
 function build-release-zip-file() {
 
+    debug-arguments $@
+
+    [ -z ${project_home} ] && fail "global variable 'project_home' not defined"
+
     local artifact_path=${project_home}/target/$(get-artifact-file-name)
 
     [ ! -f ${artifact_path}  ] && fail "project artifact $(get-artifact-file-name) not found - build the project manually"
-
-#    local skip_tests_arg
-#    ${no_tests} && skip_tests_arg="-Dmaven.test.skip=true"
-#    local maven_quiet="-q"
-#    ${verbose} && maven_quiet=""
-#    (cd ${project_home}; mvn ${maven_quiet} clean package ${skip_tests_arg}) && debug "mvn ${maven_quiet} clean package ${skip_tests_arg}" || exit 1
 
     local zip_file_base_name=$(get-artifact-base-name)-$(get-version)
     local zip_root_dir=${project_home}/target/${zip_file_base_name}
@@ -1007,6 +1072,12 @@ function do-install() {
     # process arguments
     #
 
+    #
+    # options:
+    #
+    #  --force
+    #
+
     local force=false
 
     local i=0
@@ -1047,6 +1118,16 @@ function do-release() {
 
     local mode # 'snapshot'|'minor'|'major'|'patch' or version string
 
+    #
+    # options:
+    #
+    #  --no-push
+    #  --no-tests
+    #
+
+    local do_push_option=true
+    local run_tests_option=true
+
     local i=0
     while [ ${i} -lt ${#arguments[*]} ]; do
         local arg=${arguments[${i}]}
@@ -1054,8 +1135,19 @@ function do-release() {
         if [ -z "${mode}" ]; then
             mode=${arg}
         fi
+        if [ "${arg:0:2}" = "--" ]; then
+            if [ "--no-push" = ${arg} ]; then
+                do_push_option=false
+            elif [ "--no-tests" = ${arg} ]; then
+                run_tests_option=false
+            else
+                fail "unknown option: ${arg}"
+            fi
+        fi
         ((i++))
     done
+
+    debug "do_push_option: ${do_push_option}"
 
     #
     # checking pre-requisites
@@ -1073,19 +1165,21 @@ function do-release() {
         return 0
     fi
 
-    local next_version
-    next_version=$(compute-next-version "${current_version}" "${mode}") || exit 1
-    debug "next version ${next_version}"
+    local release_version
+    release_version=$(compute-release-version "${current_version}" "${mode}") || exit 1
+    debug "release version ${release_version}"
 
-    yes "releasing ${next_version}, is this OK?" || { info "release canceled, no files were changed"; return 0; }
+    yes "releasing ${release_version}, is this OK?" || { info "release canceled, no files were changed"; return 0; }
 
-    set-version ${next_version}
+    set-version ${release_version}
 
     #
     # run the tests with the new version
     #
 
-    mvn clean test || fail "test suite failed after version increment, manual intervention required"
+    if ${run_tests_option}; then
+        mvn clean test || fail "test suite failed after version increment, manual intervention required"
+    fi
 
     #
     # tag repository
@@ -1093,9 +1187,9 @@ function do-release() {
 
     git add . && info "git add ok" || fail "git add . failed"
 
-    git commit -m "release ${next_version}" && info "git commit ok" || fail "git commit failed"
+    git commit -m "release ${release_version}" && info "git commit ok" || fail "git commit failed"
 
-    local tag=release-${next_version}
+    local tag=release-${release_version}
     local tagged
 
     if [[ ${tag} =~ SNAPSHOT ]]; then
@@ -1105,42 +1199,60 @@ function do-release() {
         info "current release is a snapshot, won't tag the repository"
         tagged=false
     else
-        git tag -m "release ${next_version}" "${tag}" && info "git tag ok, tagged with ${tag}" || fail "git tag failed"
+        git tag -m "release ${release_version}" "${tag}" && info "git tag ok, tagged with ${tag}" || fail "git tag failed"
         tagged=true
     fi
 
-    git push --follow-tags && info "git push ok" || fail "git push failed"
-
-    #
-    # If we release externally (as a zip file), we only need to create the JAR locally in the project, so we package.
-    # If we release to LOCAL_MAVEN, we install
-    #
-
-    if is-local-maven-release; then
-        mvn clean install || fail "failed to pass tests, must restore the version in pom.xml to ${current_version} manually"
+    if ${do_push_option}; then
+        git push --follow-tags && info "git push ok" || fail "git push failed"
     else
-        mvn clean package || fail "failed to pass tests, must restore the version in pom.xml to ${current_version} manually"
-        local release_zip_file_path
-        release_zip_file_path=$(build-release-zip-file) || exit 1
-        install-release ${release_zip_file_path}
+        info "got --no-push, we don't push to the remote repository"
     fi
 
-    local msg="A new ${mode} version (${next_version}) was released"
+    local release_binary_artifact
+    local maven_testing_configuration=""
+    ! ${run_tests_option} &&  maven_testing_configuration="-Dmaven.test.skip=true"
+
+    if is-local-maven-release; then
+        mvn ${maven_testing_configuration} clean install || \
+            fail "failed to pass tests, must restore the version in pom.xml to ${current_version} manually"
+
+        release_binary_artifact=${project_home}/target/$(get-artifact-file-name)
+        [ -f ${release_binary_artifact} ] || \
+            fail "release binary artifact ${release_binary_artifact} not found, something went wrong with the maven build process"
+
+    else
+        mvn ${maven_testing_configuration} clean package || \
+            fail "failed to pass tests, must restore the version in pom.xml to ${current_version} manually"
+        release_binary_artifact=$(build-release-zip-file) || exit 1
+        install-release ${release_binary_artifact}
+    fi
+
+    #
+    # increment locally to the next patch snapshot
+    #
+    current_version=$(get-version)
+    local next_local_version
+    next_local_version=$(compute-next-version "${current_version}" snapshot) || exit 1
+    debug "next local version ${next_local_version}"
+
+    yes "setting next local version ${next_local_version}, is this OK?" || return 0;
+    set-version ${next_local_version}
+
+    local msg="A new ${mode} version (${release_version}) was released"
 
     if ${tagged}; then
-
         msg="${msg}, committed to repository and tagged."
     else
         msg="${msg} and committed to repository."
     fi
 
     info ""
+    info "RELEASE SUMMARY:"
+    info ""
     info ${msg}
-    info "If you want to create an official GitHub release, use tag \"${tag}\" and the following binary: ${release_zip_file_path}"
-    info ""
-
-    info ""
-    info "TODO: ask whether to start a new major/minor/patch snapshot, and start it ..."
+    info "If you want to create an official GitHub release, use tag \"${tag}\" and binary $(basename ${release_binary_artifact})."
+    info "The local version has been incremented to ${next_local_version}."
     info ""
 }
 
