release 2.4

diff --git a/bin/operations b/bin/operations
--- a/bin/operations
+++ b/bin/operations
@@ -30,16 +30,20 @@ Commands:
 
         If 'info' is used, returns the current version information.
 
-        Makes a release by incrementing the release information appropriately, running all tests, building the final
-        artifact and installing the artifact in the appropriate repository.
+        Makes a release by incrementing the release information appropriately, running all tests,
+        tagging the repository, building the final artifact and installing the artifact in the
+        appropriate artifact repository.
 
-        If 'snapshot' is used, and the current release is a dot release, it will be incremented to the next patch
-        snapshot release. If the current release is a snapshot release, the snapshot counter will be simply
-        incremented.
+        If 'snapshot' is used, and the current release is a dot release, it will be incremented to
+        the next patch snapshot release. If the current release is a snapshot release, the
+        snapshot counter will be simply incremented.
 
-        If a version string is used, the string is checked for consistency. The release process will fail if the
-        version string is invalid or represents an older version than the current version. The repository can be
-        the local Maven repository, a directory, a remote server, etc.
+        If a version string is used, the string is checked for consistency. The release process
+        will fail if the version string is invalid or represents an older version than the current
+        version. The repository can be the local Maven repository, a directory, a remote server,
+        etc.
+
+        Also see https://kb.novaordis.com/index.php/Public_Release_Procedure_for_Projects
 
      test - internal release tools testing shortcut. Advanced users only.
 
@@ -47,10 +51,11 @@ Installation:
 
     ./src/main/bash/operations install-release-tools <project-home-directory>
 
-        The installation functionality can currently only be accessed from the original repository.
-        'install-release-tools' installs the release tools into the 'bin' subdirectory of the specified project home
-        directory. A target directory qualifies as "project home directory" if it has a Maven pom.xml in it. If an
-        older version of the release tools is already installed, 'install-release-tools' will upgrade in place.
+        The installation functionality can currently only be accessed from the original
+        repository. 'install-release-tools' installs the release tools into the 'bin' subdirectory
+        of the specified project home directory. A target directory qualifies as "project home
+        directory" if it has a Maven pom.xml in it. If an older version of the release tools is
+        already installed, 'install-release-tools' will upgrade in place.
 
 Per-Project Configuration:
 
@@ -308,13 +313,39 @@ function compute-next-version() {
     debug "major=${major}, minor=${minor}, patch=${patch}, snapshot=${snapshot}"
 
     if [ "${mode}" = "major" ]; then
-        major=$(expr ${major} + 1) || exit 1
+        #
+        # only increment if we're not a snapshot
+        #
+        if [ -z "${snapshot}" ]; then
+            major=$(expr ${major} + 1) || exit 1
+        fi
         minor=""
         patch=""
         snapshot=""
     elif [ "${mode}" = "minor" ]; then
+
         [ -z "${minor}" ] && minor=0
-        minor=$(expr ${minor} + 1) || exit 1
+        if [ -n "${snapshot}" ]; then
+            #
+            # we're a snapshot
+            #
+            if [ -n "${patch}" ]; then
+                #
+                # we're a patch snapshot, so increment the minor
+                #
+                minor=$(expr ${minor} + 1) || exit 1
+            else
+                debug "we're a minor snapshot, we don't increment the minor"
+                #
+                # we're a minor snaps
+                #
+            fi
+        else
+            #
+            # we're not a snapshot
+            #
+            fail "incrementing a non-snapshot minor NOT YET IMPLEMENTED"
+        fi
         patch=""
         snapshot=""
     elif [ "${mode}" = "patch" ]; then
@@ -1039,6 +1070,26 @@ function do-release() {
     set-version ${next_version}
 
     #
+    # run the tests with the new version
+    #
+
+    mvn clean test || fail "test suite failed after version increment, manual intervention required"
+
+    #
+    # tag repository
+    #
+
+    git add . && info "git add ok" || fail "git add . failed"
+
+    git commit -m "release ${next_version}" && info "git commit ok" || fail "git commit failed"
+
+    local tag=release-${next_version}
+
+    git tag -m "release ${next_version}" "${tag}" && info "git tag ok, tagged with ${tag}" || fail "git tag failed"
+
+    git push --follow-tags && info "git push ok" || fail "git push failed"
+
+    #
     # If we release externally (as a zip file), we only need to create the JAR locally in the project, so we package.
     # If we release to LOCAL_MAVEN, we install
     #
@@ -1053,12 +1104,14 @@ function do-release() {
     fi
 
     info ""
-    info "###########################################################################################"
-    info "#"
-    info "#    A new ${mode} version (${next_version}) was released locally, you may want to commit and push git #"
-    info "#"
-    info "###########################################################################################"
+    info "A new ${mode} version (${next_version}) was released, committed to repository and tagged."
+    info "If you want to create an official GitHub release, use tag \"${tag}\" and the following binary: ${release_zip_file_path}"
     info ""
+
+    info ""
+    info "TODO: ask whether to start a new major/minor/patch snapshot, and start it ..."
+    info ""
+
 
 }
 
