clad - esa integration

diff --git a/bin/operations b/bin/operations
--- a/bin/operations
+++ b/bin/operations
@@ -311,9 +311,19 @@ function configure-run-wrapper()
 
 #
 # heuristics to find the main class of the application. Returns the main class in the format "com.example.Main"
+# If the project declares a dependency on clad, it assumes the main class is provided by clad, otherwise it brute-force
+# recursively searches for a "public static void main"
 #
 function find-main-class()
 {
+    local pom_file=${project_home}/pom.xml
+    [ -f ${pom_file} ] || fail "pom.xml file ${pom_file} not found"
+
+    if grep -q  "<groupId>io\.novaordis\.clad</groupId>" ${pom_file}; then
+        echo "io.novaordis.clad.CommandLineApplication"
+        return 0
+    fi
+
     local src_dir=${project_home}/src/main
     local line
     line=$(grep -r "public static void main" ${src_dir}/* | head -n 1) || fail "failed to grep ${src_dir}/*"
@@ -363,7 +373,7 @@ function build-installation-zip-file() {
 #    ${no_tests} && skip_tests_arg="-Dmaven.test.skip=true"
 #    local maven_quiet="-q"
 #    ${verbose} && maven_quiet=""
-#    (cd ${project_home}; mvn ${maven_quiet} clearStateInSubclass package ${skip_tests_arg}) && debug "mvn ${maven_quiet} clearStateInSubclass package ${skip_tests_arg}" || exit 1
+#    (cd ${project_home}; mvn ${maven_quiet} clean package ${skip_tests_arg}) && debug "mvn ${maven_quiet} clean package ${skip_tests_arg}" || exit 1
 
     local zip_file_base_name=$(get-artifact-base-name)-$(get-version)
     local zip_root_dir=${project_home}/target/${zip_file_base_name}
@@ -439,7 +449,7 @@ function install()
 
         ! ${force} && fail "${application_home_dir} already installed. Use '-f' or '--force' to overwrite"
 
-        # --force was used, remove the existing directory for a clearStateInSubclass installation
+        # --force was used, remove the existing directory for a clean installation
         rm -r ${application_home_dir} && \
             debug "removed existing ${application_home_dir}" || \
             fail "failed to remove existing ${application_home_dir}"
